Connecting Game State to UI
scottysseus/rustfield-revival pull request #14
Opened 2021-12-15 03:05 UTC by nmoadev

IGNORE: nmoadev.full-fix. This PR covers that branch, but resolves conflicts

* Load models from glb files
* Click on mesh to open "project selection" window
* Fancy new next turn button
* Lots of state plumbing through the app

PENDING ISSUES
* only the last position for a building seems to be respected
* Camera resets on state change

2021-12-15 08:11 UTC, libjared requested changes
Re: camera reset, I opened #15

2021-12-15 08:11 UTC, hypevhs commented on src/components/view/MapLocation.tsx
> +import { Tile } from '../game_logic'
You have several invalid paths (check the linter)

2021-12-15 08:11 UTC, hypevhs commented on src/do-three-js.ts
> +  const canvReference = document.getElementById('threejscanvas')
What is this file for?

2021-12-15 21:23 UTC, scottysseus approved these changes
We can keep iterating on the reducers. I can see those growing large enough to warrant their own file(s), for example. Looks awesome so far!

2021-12-16 01:37 UTC, scottysseus commented on src/do-three-js.ts
> +  const canvReference = document.getElementById('threejscanvas')
We can probably get rid of it later; I'll keep it around for now

2021-12-16 02:58 UTC, libjared commented on src/components/GameDisplay.tsx
> +      {/* eslint-disable-next-line react/jsx-pascal-case */}
This can be removed

2021-12-16 02:58 UTC, libjared commented on src/components/view/Map.tsx
> +import { uiDispatcher, UiState } from './GameDisplay'
These are the other two invalid paths I was mentioning.

2021-12-16 23:20 UTC, libjared approved these changes

2021-12-16 23:24 UTC, merged